config/routes.rb
Rails.application.routes.draw do

  get 'invite/index'
  match '/invite' => 'invite#index', via: [:get, :post]
  post 'invite/request_invite'
  get 'invite/request_sent'

  get 'statement/index'
  match '/statement' => 'statement#index', via: [:get, :post]
  get 'website_terms/index'
  match '/website_terms' => 'statement#index', via: [:get, :post]
  get 'customer_terms/index'
  match '/customer_terms' => 'statement#index', via: [:get, :post]
  get 'privacy/index'
  match '/privacy' => 'privacy#index', via: [:get, :post]

  get 'locations/suburb_state_postcode'

  get 'users/apply_now'
  post 'users/apply'
  get 'users/email_sent'
  get 'users/password_reset_sent'

  get 'home/index'

  get 'mates/index'

  get 'messages/index'
  get 'messages/activation_code'
  get 'messages/contact_form'
  get 'inspections_leads/ajax_update'
  post 'inspections_leads/delete_inspection_leads'
  post 'inspections_leads/set_rating'

  devise_for :users, :controllers => { :registrations => "users/registrations", :passwords => "users/passwords" }

  resources :today
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :inspections_lead
  resources :email_templates do
    collection do
      post :ipad_email_setting
    end
  end

  resources :user_profiles do
    collection do
      get :ajax_update
      post :upload
      get :get_user_profile
    end
  end

  resources :inspections do
    collection do
      get :ajax_update
      post :upload
      post :upload_attachment
      get :delete_property_file
      post :upload_property_file
      get :get_leads_emails_by_user
      post :send_bulk_email
      post :filter_inspection_leads
      post :inspection_sold
      post :create_default
      post :render_inspection
      post :render_panel_heading
      post :filter
    end
  end
  resources :leads do
    collection do
      get :ajax_update
      post :search
      post :delete_leads
      post :send_bulk_email
      post :upload_file
    end
  end

  namespace :api do
    namespace :v1 do
      resources :inspections do
        collection do
          get :get_inspections_by_user
        end
      end
      resources :leads do
        collection do
          get :get_leads_by_inspection
          get :get_all_leads_by_user
          post :upload_leads_for_inspection
        end
      end
      resources :users do
        collection do
          get :login
        end
      end
    end
  end

  root 'home#index'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/property.rb
class Property < ActiveRecord::Base
  has_one :inspection

  def suburb_and_postcode

  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_developer.html.haml
.panel.with-nav-tabs.panel-default
  .panel-heading
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#property_highlight_tab"} Property Highlight
      %li
        %a{"data-toggle" => "tab", :href => "#developer_info_tab"} Developer Information
      %li
        %a{"data-toggle" => "tab", :href => "#file_tab"} File Download
  .panel-body
    .tab-content
      #property_highlight_tab.tab-pane.fade.in.active        
        = form_for(@property) do |f|
          - if @property.errors.any?
            #error_explanation
              %h2
                = pluralize(@property.errors.count, "error") 
                prohibited this product from being saved:
              %ul
              - @property.errors.full_messages.each do |msg|
                %li 
                  = msg

          %h4 Property Details        
          %hr
          .form-group
            = f.label :address
            = f.text_field :address, class: "form-control", :placeholder => "Property Address"
          .form-group
            .row
              .col-md-6
                = f.label :property_type
                = f.select :property_type, options_for_select(Rails.application.config.property_types.sort), {:include_blank => false}, {:class => "form-control"}
              .col-md-6
                = f.label :sales_type
                = f.select :sales_type, options_for_select(Rails.application.config.sales_types), {:include_blank => false}, {:class => "form-control"}
          .form-group
            .row
              .col-md-4
                = f.label :bedroom
                = f.select :bedroom, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
              .col-md-4
                = f.label :bathroom
                = f.select :bathroom, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
              .col-md-4
                = f.label :parking
                = f.select :parking, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
          .form-group
            .row
              .col-md-6
                = f.label :price
                .input-group
                  %span.input-group-addon 
                    %span.glyphicon.glyphicon-usd{"aria-hidden"=>"true"}
                  = f.text_field :price, class: "form-control", :placeholder => "Property Price"
                  %span.input-group-addon .00
              .col-md-6
                = f.label :date
                .input-group
                  %span.input-group-addon 
                    %span.glyphicon.glyphicon-time{"aria-hidden"=>"true"}
                  = f.text_field :property_date, class: "form-control datepicker", :placeholder => "List date"
          .form-group
            .row
              .col-md-6
                = f.label :floor_area
                .input-group
                  = f.text_field :floor_area, class: "form-control", :placeholder => "Floor area"
                  %span.input-group-addon
                    m
                    %sup 2
              .col-md-6
                = f.label :land_area
                .input-group
                  = f.text_field :land_area, class: "form-control", :placeholder => "Land area"
                  %span.input-group-addon
                    m
                    %sup 2
          %br
          %h4 Property Description
          %hr
          .form-group
            = f.label :headline
            = f.text_field :headline, class: "form-control", :placeholder => "Headline"
          .form-group
            = f.label :description
            = f.text_area :description, class: "form-control", :placeholder => "Describe the property"
          .form-group
            = f.label :features
            = f.text_area :features, class: "form-control", :placeholder => "Features"
          .form-group
            = f.label :finishes
            = f.text_field :finishes, class: "form-control", :placeholder => "Finishes"
          .form-group
            = f.label :fee
            = f.text_field :fee, class: "form-control", :placeholder => "Fee"
          .form-group
            = f.label "Q&A"
            = f.text_area :q_and_a, class: "form-control", :placeholder => "Q&A"
          .form-group
            = f.label :note
            = f.text_area :note, class: "form-control", :placeholder => "Note"
          = button_tag "Save", :class => "btn btn-primary"
      #developer_info_tab.tab-pane.fade
        = form_for(@property) do |f|
          - if @property.errors.any?
            #error_explanation
              %h2
                = pluralize(@property.errors.count, "error") 
                prohibited this product from being saved:
              %ul
              - @property.errors.full_messages.each do |msg|
                %li 
                  = msg

          = button_tag "Save", :class => "btn btn-primary"
      #file_tab.tab-pane.fade bbb



:javascript
  $( document ).ready(function() {
    $(".datepicker").datepicker({
      dateFormat: "dd/mm/yy"
    });
  });

app/views/properties/_form.html.haml
.panel.with-nav-tabs.panel-default
  .panel-heading
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#property_highlight_tab"} Property Highlight
      %li
        %a{"data-toggle" => "tab", :href => "#developer_info_tab"} Developer Information
      %li
        %a{"data-toggle" => "tab", :href => "#file_tab"} File Download
  .panel-body
    .tab-content
      #property_highlight_tab.tab-pane.fade.in.active        
        = form_for(@property) do |f|
          - if @property.errors.any?
            #error_explanation
              %h2
                = pluralize(@property.errors.count, "error") 
                prohibited this product from being saved:
              %ul
              - @property.errors.full_messages.each do |msg|
                %li 
                  = msg

          %h4 Property Details        
          %hr
          .form-group
            = f.label :street_address
            = f.text_field :street_address, class: "form-control", :placeholder => "Property Address"
          .form-group
            .row
              .col-md-6
                = f.label :property_type
                = f.select :property_type, options_for_select(Rails.application.config.property_types.sort), {:include_blank => false}, {:class => "form-control"}
              .col-md-6
                = f.label :sales_type
                = f.select :sales_type, options_for_select(Rails.application.config.sales_types), {:include_blank => false}, {:class => "form-control"}
          .form-group
            .row
              .col-md-4
                = f.label :bedroom
                = f.select :bedroom, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
              .col-md-4
                = f.label :bathroom
                = f.select :bathroom, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
              .col-md-4
                = f.label :parking
                = f.select :parking, options_for_select((0..10).to_a), {:include_blank => false}, {:class => "form-control"}
          .form-group
            .row
              .col-md-6
                = f.label :price
                .input-group
                  %span.input-group-addon 
                    %span.glyphicon.glyphicon-usd{"aria-hidden"=>"true"}
                  = f.text_field :price, class: "form-control", :placeholder => "Property Price"
                  %span.input-group-addon .00
              .col-md-6
                = f.label :date
                .input-group
                  %span.input-group-addon 
                    %span.glyphicon.glyphicon-time{"aria-hidden"=>"true"}
                  = f.text_field :property_date, class: "form-control datepicker", :placeholder => "List date"
          .form-group
            .row
              .col-md-6
                = f.label :floor_area
                .input-group
                  = f.text_field :floor_area, class: "form-control", :placeholder => "Floor area"
                  %span.input-group-addon
                    m
                    %sup 2
              .col-md-6
                = f.label :land_area
                .input-group
                  = f.text_field :land_area, class: "form-control", :placeholder => "Land area"
                  %span.input-group-addon
                    m
                    %sup 2
          %br
          %h4 Property Description
          %hr
          .form-group
            = f.label :headline
            = f.text_field :headline, class: "form-control", :placeholder => "Headline"
          .form-group
            = f.label :description
            = f.text_area :description, class: "form-control", :placeholder => "Describe the property"
          .form-group
            = f.label :features
            = f.text_area :features, class: "form-control", :placeholder => "Features"
          .form-group
            = f.label :finishes
            = f.text_field :finishes, class: "form-control", :placeholder => "Finishes"
          .form-group
            = f.label :fee
            = f.text_field :fee, class: "form-control", :placeholder => "Fee"
          .form-group
            = f.label "Q&A"
            = f.text_area :q_and_a, class: "form-control", :placeholder => "Q&A"
          .form-group
            = f.label :note
            = f.text_area :note, class: "form-control", :placeholder => "Note"
          = button_tag "Save", :class => "btn btn-primary"
      #developer_info_tab.tab-pane.fade
        - developer = @property.developer
        - developer = Developer.new if developer.blank?
        = form_for(developer) do |f|
          - if developer.errors.any?
            #error_explanation
              %h2
                = pluralize(developer.errors.count, "error") 
                prohibited this product from being saved:
              %ul
              - developer.errors.full_messages.each do |msg|
                %li 
                  = msg

          %h4 Developer Details        
          %hr
          .form-group
            = hidden_field_tag 'property_id', @property.id
          .form-group
            = f.label :company
            = f.text_field :company, class: "form-control", :placeholder => "Company"
          .form-group
            = f.label :contact
            = f.text_field :contact, class: "form-control", :placeholder => "Contact"
          .form-group
            = f.label :title, :class => "control-label"
            = f.select :title, Rails.application.config.common_titles, {:include_blank => true}, {:class => "form-control input-sm"}
          .form-group
            = f.label :phone
            = f.text_field :phone, class: "form-control", :placeholder => "Phone"
          .form-group
            = f.label :website
            = f.text_field :website, class: "form-control", :placeholder => "Website"
          .form-group
            = f.label :display_address
            = f.text_field :display_address, class: "form-control", :placeholder => "Display Address"

          = button_tag "Save", :class => "btn btn-primary"
      #file_tab.tab-pane.fade bbb



:javascript
  $( document ).ready(function() {
    $(".datepicker").datepicker({
      dateFormat: "dd/mm/yy"
    });
  });

app/views/properties/edit.html.haml
.container
  .row
    .col-md-3
      =render '/layouts/sidebar'
    .col-md-9
      %h1
        Edit new property
      = render 'form'

app/views/properties/index.html.haml
.container
  .row
    .col-md-3
      =render '/layouts/sidebar'
    .col-md-9
      .panel.with-nav-tabs.panel-default
        .panel-heading
          %ul.nav.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#tab1default"} My Stock
            %li
              %a{"data-toggle" => "tab", :href => "#tab2default"} Mate Property Market
            %li
              %a{"data-toggle" => "tab", :href => "#tab3default"} Public Property Market
            %li.dropdown
              %a{"data-toggle" => "dropdown", :href => "#"}
                Customised Groups
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a{"data-toggle" => "tab", :href => "#tab4default"} Favourite Properties
                %li
                  %a{"data-toggle" => "tab", :href => "#tab5default"} Archived Properties
        .panel-body
          .tab-content
            = link_to new_property_path do 
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            #tab1default.tab-pane.fade.in.active
              %table.table.table-striped
                %thead
                  %tr
                    %th #
                    %th Address
                    %th Type
                    %th Details
                    %th Price
                    %th Sales Type
                    %th Date
                    %th Area
                    %th Action
                %tbody
                  - @properties.each_with_index do |p, idx| 
                    %tr
                      %td 
                        = idx + 1
                      %td 
                        =p.address
                      %td 
                        =p.property_type
                      %td
                        = p.bedroom
                      %td 
                        =p.price
                      %td 
                        =p.sales_type
                      %td 
                        =p.property_date
                      %td
                        = p.floor_area
                      %td.text-center
                        %a.btn.btn-success.btn-xs{:href => property_path(p)}
                          %span.glyphicon.glyphicon-list-alt
                        %a.btn.btn-info.btn-xs{:href => edit_property_path(p)}
                          %span.glyphicon.glyphicon-edit
                        %a{:confirm=>"Are you sure?", :class=>"btn btn-xs btn-danger", :rel=>"nofollow", "data-method"=>"delete", :href=>property_path(p)}
                          %span.glyphicon.glyphicon-remove

            #tab2default.tab-pane.fade Mate Property Market
            #tab3default.tab-pane.fade Public Property Market
            #tab4default.tab-pane.fade Favourite Properties
            #tab5default.tab-pane.fade Archived Properties

app/views/properties/new.html.haml
.container
  .row
    .col-md-3
      =render '/layouts/sidebar'
    .col-md-9
      %h1
        Create new property
      = render 'form'

app/views/properties/show.html.haml
.container
  .row
    .col-md-3
      =render '/layouts/sidebar'
    .col-md-9
      %h1 Property Details
      %dl.dl-horizontal
        %dt Address
        %dd
          = @property.address
        %dt Property type
        %dd
          = @property.property_type
        %dt Bedroom
        %dd
          = @property.bedroom
        %dt Bathroom
        %dd
          = @property.bathroom
        %dt Parking
        %dd
          = @property.parking
        %dt Price
        %dd
          = "$#{@property.price}"
        %dt Sales type
        %dd
          = @property.sales_type
        %dt Date
        %dd
          = @property.property_date
        %dt Floor area
        %dd
          = @property.floor_area
        %dt Land area
        %dd
          = @property.land_area
        %dt Description
        %dd
          = @property.description