config/routes.rb
Rails.application.routes.draw do

  get 'invite/index'
  match '/invite' => 'invite#index', via: [:get, :post]
  post 'invite/request_invite'
  get 'invite/request_sent'

  get 'statement/index'
  match '/statement' => 'statement#index', via: [:get, :post]
  get 'website_terms/index'
  match '/website_terms' => 'statement#index', via: [:get, :post]
  get 'customer_terms/index'
  match '/customer_terms' => 'statement#index', via: [:get, :post]
  get 'privacy/index'
  match '/privacy' => 'privacy#index', via: [:get, :post]

  get 'locations/suburb_state_postcode'

  get 'users/apply_now'
  post 'users/apply'
  get 'users/email_sent'
  get 'users/password_reset_sent'

  get 'home/index'

  get 'mates/index'

  get 'messages/index'
  get 'messages/activation_code'
  get 'messages/contact_form'
  get 'inspections_leads/ajax_update'
  post 'inspections_leads/delete_inspection_leads'
  post 'inspections_leads/set_rating'

  devise_for :users, :controllers => { :registrations => "users/registrations", :passwords => "users/passwords" }

  resources :today
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :inspections_lead
  resources :email_templates do
    collection do
      post :ipad_email_setting
    end
  end

  resources :user_profiles do
    collection do
      get :ajax_update
      post :upload
      get :get_user_profile
    end
  end

  resources :inspections do
    collection do
      get :ajax_update
      post :upload
      post :upload_attachment
      get :delete_property_file
      post :upload_property_file
      get :get_leads_emails_by_user
      post :send_bulk_email
      post :filter_inspection_leads
      post :inspection_sold
      post :create_default
      post :render_inspection
      post :render_panel_heading
      post :filter
    end
  end
  resources :leads do
    collection do
      get :ajax_update
      post :search
      post :delete_leads
      post :send_bulk_email
      post :upload_file
    end
  end

  namespace :api do
    namespace :v1 do
      resources :inspections do
        collection do
          get :get_inspections_by_user
        end
      end
      resources :leads do
        collection do
          get :get_leads_by_inspection
          get :get_all_leads_by_user
          post :upload_leads_for_inspection
        end
      end
      resources :users do
        collection do
          get :login
        end
      end
    end
  end

  root 'home#index'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :user
  has_many :inspections_leads, :dependent => :delete_all
  has_many :leads, through: :inspections_leads
  has_many :email_templates, :dependent => :delete_all

  after_initialize :init
  validates :user_id, :street_address, :state, :postcode, :suburb, :on_type, presence: true, :allow_blank => false

  def init
    # self.number  ||= 0.0           #will set the default value only if it's nil
    # self.address ||= build_address #let's you set a default association
    self.send_file = true if self.send_file.nil?
    self.property_files = "" if self.property_files.nil?
    self.property_images = URI::encode("#{Rails.configuration.action_controller.default_url_options[:host]}/assets/default_inspection_image.png") if self.property_images.nil?
  end

  def suburb_state_postcode
    "#{self.suburb}, #{self.state}, #{self.postcode}"
  end

  def get_full_address
    if self.full_address.blank?
      "#{self.street_address.titleize}, #{self.suburb} #{self.state} #{self.postcode}"
    else
      self.full_address
    end
  end

  def property_images_url
    if self.property_images.start_with?("http") or self.property_images.start_with?("//")
      self.property_images
    else
      "#{Rails.configuration.action_controller.default_url_options[:host]}/uploads/#{self.user.id}/#{self.id}/#{self.property_images}"
    end
  end

  def self.upload_file_dir(user_id, inspection_id)
    Rails.root.join('public', 'uploads', user_id.to_s, inspection_id.to_s)
  end

  # Create default inspection(Sale/Lease)
  def self.create_default(on_type, user_id)
    inspection = Inspection.new
    inspection.user_id = user_id
    inspection.street_address = "Edit Address"
    inspection.suburb = "Edit Suburb"
    inspection.state = "State"
    inspection.postcode = "Postcode"
    inspection.on_type = on_type
    inspection.status = on_type == 'Lease' ? 'For Lease' : 'For Sale'
    # inspection.last_updated = Time.zone.now
    return inspection
  end

  def property_file_url(property_file)
    if property_file == "sample_contract.pdf"
      URI::encode("#{Rails.configuration.action_controller.default_url_options[:host]}/#{property_file}")
    else
      URI::encode("#{Rails.configuration.action_controller.default_url_options[:host]}/uploads/#{self.user.id}/#{self.id}/#{property_file}")
    end
  end

  def self.property_file_path(user_id, inspection_id, property_file)
    if property_file == "sample_contract.pdf"
      Rails.root.join('public', property_file)
    else
      Rails.root.join('public', 'uploads', user_id.to_s, inspection_id.to_s, property_file)
    end
  end

  def property_files_to_array
    if self.property_files.blank?
      return Array.new
    else
      return self.property_files.split(',')
    end
  end

  def add_property_file(property_file)
    property_files = self.property_files_to_array << property_file
    self.property_files = property_files.join(',')
  end

end

app/controllers/api/v1/inspections_controller.rb
module Api
  module V1
    # class InspectionsController < Api::BaseController
    class InspectionsController < ApplicationController

      # GET /api/{plural_resource_name}
      def index
        logger.debug "params: #{params.inspect}"
        @inspections = Inspection.where(query_params)
      end

      def get_inspections_by_user
        logger.debug "in get_inspections_by_user..."
        @error = ""
        user_id = params[:user_id]
        device_id = params[:device_id]
        # Return leads if has_leads is true
        @has_leads = params[:has_leads]
        if not User.exists?(user_id)
          @error = "User not found"
        else
          user = User.find(user_id)
          if user.device_id != device_id
            @error = "User with wrong device id"
          else
            @inspections = Inspection.where(:user_id => user_id, :status => Rails.application.config.send_to_ipad_types)
          end
        end
      end

      private

        def inspection_params
          params.require(:inspection).permit(:id, :street_address, :suburb, :state, :postcode, :property_images, :on_type)
        end

      #   def query_params
      #     # this assumes that an album belongs to an artist and has an :artist_id
      #     # allowing us to filter by this
      #     params.permit(:id, :street_address)
      #   end

    end
  end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token
  include ApplicationHelper

  # GET /inspections
  # GET /inspections.json
  def index
    status = params[:status]
    @type = params[:type].blank? ? "Sale" : params[:type]
    @inspections = filter_inspections(status, @type)

    respond_to do |format|
      format.html
      format.js
    end

  end

  def filter
    status = params[:status]
    @type = params[:type].blank? ? "Sale" : params[:type]
    @inspections = filter_inspections(status, @type)
    respond_to do |format|
      format.js
    end
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = Inspection.new(inspection_params)
    suburb, postcode = params[:inspection][:suburb_and_postcode].split(',')
    @inspection.suburb = suburb.strip
    @inspection.postcode = postcode.strip
    uploaded_io = params[:inspection][:property_images]
    logger.debug "uploaded_io: #{uploaded_io.inspect}"
    filename = uploaded_io.original_filename
    filename = sanitize_filename(filename)
    @inspection.property_images = filename

    respond_to do |format|
      if @inspection.save
        dir = Rails.root.join('public', 'uploads', @inspection.id.to_s)
        FileUtils.mkdir_p(dir) unless File.directory?(dir)
        File.open("#{dir}/#{filename}", 'wb') do |file|
          file.write(uploaded_io.read)
        end
        format.html { redirect_to "/inspections", notice: 'Inspection was successfully created.' }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_default
    status = params[:status]
    @type = params[:type]
    @inspection = Inspection.create_default(@type, current_user.id)
    @inspection.save
    @inspections = filter_inspections(status, @type)

    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    if @inspection.destroy
      # clear uploads folder
      dir = Inspection.upload_file_dir(current_user.id, @inspection.id)
      FileUtils.rm_rf(dir) if File.exists?(dir)
    end

    respond_to do |format|
      format.html { redirect_to inspections_url, notice: 'Inspection was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def ajax_update
    attr_name = params["name"].dup
    attr_name.slice!("_#{params["pk"]}")
    attr_value = params["value"]
    ins = Inspection.find(params["pk"])
    json_data = Hash.new
    saved = nil
    if attr_name == "suburb_state_postcode"
      if not attr_value.blank? and attr_value.split(',').count == 3
        ins.suburb = attr_value.split(',')[0].strip
        ins.state = attr_value.split(',')[1].strip
        ins.postcode = attr_value.split(',')[2].strip
        saved = ins.save
      else
        json_data[params["name"]] = ins.suburb_state_postcode
        json_data['updated?'] = false
      end
    else
      ins.attributes = {attr_name => attr_value}
      saved = ins.save 
    end
    json_data.merge!(ins.attributes)
    respond_to do |format|
      format.json { 
        if saved.nil? 
          render :json => json_data.to_json 
        elsif saved
          render :status => 227, :json => ins
        else
          json_data = {:status => 'error', :msg => ins.errors.full_messages.first}
          render :status => 200, :json => json_data
        end
      }
    end
  end

  # upload image
  def upload
    logger.debug "uploading ..."
    # if not params[:property_images].blank?
    #   name = "property_images"
    # end
    name = "property_images"
    inspection = Inspection.find(params[:inspection_id])
    uploaded_io = params[:file]
    # file_name = uploaded_io.original_filename
    file_name = uploaded_io.original_filename.split('.')[0] 
    file_type = uploaded_io.original_filename.split('.')[1]
    file_name = "#{file_name}_#{current_user.id}_#{inspection.id}.#{file_type}"
    file_name = sanitize_filename(file_name)
    dir = Inspection.upload_file_dir(current_user.id, inspection.id)
    FileUtils.mkdir_p(dir) unless File.directory?(dir)
    File.open("#{dir}/#{file_name}", 'wb') do |file|
      file.write(uploaded_io.read)
    end
    old_file_name = inspection.property_images
    logger.debug "name: #{name}, file_name: #{file_name}"
    inspection.update_attribute(name, file_name)
    if file_name != old_file_name
      # delete file on disk
      file_path = Inspection.property_file_path(current_user.id, inspection.id, old_file_name)
      File.delete(file_path) if File.exist?(file_path)
    end
    inspection.save
    redirect_to :back
  end

  # Uploaded attachment is now added as property file, saved to property files list
  def upload_attachment
    inspection = Inspection.find(params[:inspection_id])
    upload_io = params[:upload_file]
    @upload_attachment_name = upload_io.original_filename 
    @upload_attachment_name = sanitize_filename(@upload_attachment_name)
    # file_type = uploaded_io.original_filename.split('.')[1]
    # file_name = "#{name}_#{current_user.id}_#{inspection.id}.#{file_type}"
    # TODO make sure uploaded external file doesn't conflict existing files
    dir = Inspection.upload_file_dir(current_user.id, inspection.id)
    FileUtils.mkdir_p(dir) unless File.directory?(dir)
    File.open("#{dir}/#{@upload_attachment_name}", 'wb') do |file|
      file.write(upload_io.read)
    end
    # add as property file, saved to property files list
    inspection.add_property_file(@upload_attachment_name)
    inspection.save

    respond_to do |format|
      format.html {
        render :nothing => true, :status => 200, :content_type => 'text/html'
      }
      format.js
    end
  end

  def delete_property_file
    @property_file_name = params[:property_file_name]
    @inspection = Inspection.find(params[:inspection_id])
    property_files = @inspection.property_files_to_array
    property_files.delete @property_file_name
    @inspection.property_files = property_files.join(',')
    if @inspection.save
      # delete file on disk
      file_path = Inspection.property_file_path(current_user.id, @inspection.id, @property_file_name)
      File.delete(file_path)
    end

  end

  # Upload files
  def upload_property_file
    logger.debug "upload_property_file ..."
    @inspection = Inspection.find(params[:inspection_id])
    # uploaded_io = params["property_file"]
    uploaded_io = params[:file]
    file_name = uploaded_io.original_filename
    file_name = sanitize_filename(file_name)
    # dir = Rails.root.join('public', 'uploads', @inspection.id.to_s)
    dir = Inspection.upload_file_dir(current_user.id, @inspection.id)
    FileUtils.mkdir_p(dir) unless File.directory?(dir)
    file_path = "#{dir}/#{file_name}"
    error = nil
    if File.exist?(file_path)
      error = "#{file_name} has been uploaded. Please rename the file and upload it again."
    else
      File.open(file_path, 'wb') do |file|
        file.write(uploaded_io.read)
      end
      # property_files = @inspection.property_files_to_array
      # property_files << file_name
      # @inspection.property_files = property_files.join(',')
      @inspection.add_property_file(file_name)
      @inspection.save
      # redirect_to :back
      # render :status => 400, :error => "ERROR"
    end
    respond_to do |format|
      format.json {
        logger.debug "returning 400, error: #{error}"
        if error
          render :nothing => true, :status => 520
        else
          render :nothing => true, :status => 200
        end
      }
    end
  end

  def get_leads_emails_by_user
    user = User.find(params[:user_id])
    @leads = user.leads
  end

  def send_bulk_email
    logger.debug "in send_bulk_email..."
    template_type = params[:template_type]
    inspection_id = params[:inspection_id]
    inspection = Inspection.find(inspection_id)
    user_id = params[:user_id]
    recipients = params["recipients_#{inspection_id}"]
    subject = params[:subject]
    orig_body = params[:body]
    # property files
    property_files = params[:property_files].blank? ? [] : params[:property_files]
    attached_files = Hash.new
    property_files.each do |property_file|
      next if property_file.blank?
      # attached_files[property_file] = Inspection.property_file_path(current_user.id, inspection_id, property_file)
      attached_files[property_file] = inspection.property_file_url(property_file)
    end
    # uploaded external files
    # upload_files = params[:upload_files].blank? ? [] : params[:upload_files]
    # upload_files.each do |upload_file|
    #   attached_files[upload_file.original_filename] = inspection.property_file_url(upload_file.original_filename)
    # end

    user = User.find(user_id)
    failed_recipients = []
    recipients_array = recipients.split(',')
    recipients_array.each do |recipient|
      lead = inspection.leads.where(:email => recipient).first
      dear_lead_name = lead.blank? ? 'Sir/Madam' : lead.first_name

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_bulk_email.html.haml
%div{:id=>"inline_bulk_email_#{inspection.id}"}
  // File Send default settings
  - subject = Rails.application.config.email_setting_fs_subject.gsub('[ADDRESS]', inspection.get_full_address)
  //- body = Rails.application.config.email_setting_file_send_body1 % [inspection.get_full_address, current_user.full_name, current_user.business_name, current_user.telephone, current_user.fax, current_user.mobile, current_user.website]
  - body = Rails.application.config.email_setting_bulk_email_signature.gsub("[AGENT NAME]", current_user.full_name).gsub("[AGENT EMAIL]", current_user.email).gsub("[AGENT MOBILE]", current_user.mobile).gsub("[AGENT COMPANY]", current_user.business_name)
  = form_tag  "/inspections/send_bulk_email", class: "nifty_form", multipart: true, :inspection_id=>inspection.id, :onsubmit=>"pre_submit(event)", :remote=>true do
    %table.table
      %tr
        %td.title
          %h4
            Send Email
      %tr
        %td.recipients
          %span.to
            To
          %span.recipients
            = text_field_tag "recipients_#{inspection.id}", nil, :size => 40, "data-provider" => "typeahead", :inspection_id => inspection.id, :placeholder => 'Add recipient'
      %tr
        %td.subject
          = hidden_field_tag :inspection_id, inspection.id
          = hidden_field_tag :user_id, current_user.id
          %span.subject_label
            Subject
          %span.subject_input
            = text_field_tag :subject, subject, :size => 40
          %span.templates
            = select_tag :template_type, options_for_select(Rails.application.config.email_setting_select_types), {:class => "form-control input-sm hide", :onchange => "select_template_type(event)"}
      %tr
        %td.message
          = text_area_tag :body, body, :rows => 10, :class => "form-control input-sm"
      %tr
        %td.bottom
          %span.attachment
            .form-group
              = label_tag :attachments
              = select_tag "property_files[]", options_for_select(inspection.property_files.split(','), inspection.property_files.split(',')), {:class => "form-control input-sm bulk_email_files", :multiple => "multiple", :inspection_id => inspection.id}
          //%span.external_files
          //  .form-group
          //    = label_tag :upload_files
          //    //= file_field_tag "upload_files[]", class: "multi maxsize-10240", :multiple=>true, :maxlength=>"10"
          //    = file_field_tag "upload_files[]"
          //    = file_field_tag "upload_files[]"
          //    = file_field_tag "upload_files[]"
          %span.notification
          %span.send
            %button{:class => "btn btn-primary bulk-send", :type => "submit", :name => "commit"}
              %i.fa.fa-paper-plane.email_sending
              Send
            //= submit_tag :send, :class => "btn btn-primary" 

  .upload_attachment_form
    %a.bulk_email_upload_files{:href => "#upload_files_colorbox", :inspection_id=>inspection.id, :onclick => "bulk_email_upload_files(event)"}
      %i.fa.fa-plus.fa-lg{:inspection_id=>inspection.id}

            
%script
  inspection_id = "#{inspection.id}";
  // email_settings = {"File Send": {'subject': "#{Rails.application.config.email_setting_file_send_subject}"}};
  email_settings = {};
  email_settings[""] = {};
  email_settings[""]["subject"] = "";
  email_settings[""]["body"] = "";
  email_settings["File Send"] = {};
  email_settings["File Send"]["subject"] = "#{Rails.application.config.email_setting_file_send_subject % inspection.street_address}";
  email_settings["File Send"]["body"] = "";

:javascript
  // Trigger change event to init the select box 
  $(document).bind('cbox_complete', function(){
    $('#colorbox select#email_template_template_type').val('File Send');
    $('span.notification').html('');
    $('#colorbox select#email_template_template_type').trigger('change');
  });

  function select_template_type(event) {
    selected_val = $('#colorbox select#email_template_template_type option:selected').val();
    $('#colorbox input#email_template_subject').val(email_settings[selected_val]['subject']);
    $('#colorbox textarea#email_template_body').val(email_settings[selected_val]['body']);
  }

  function pre_submit(event) {
    form = event.target;
    inspection_id = $(form).attr('inspection_id');
    $('i.email_sending').removeClass('fa-paper-plane').addClass('fa-spinner fa-pulse');
    $('button.bulk-send').attr('disabled','disabled');
    //$("a.bulk_email.inline").colorbox.close();
  }

app/views/inspections/_for_sale.html.haml
= javascript_include_tag "for_sale"
.row.tab-head-container
  .col-md-12
    = form_tag "/inspections/filter", class: "form-inline tab-head", remote: true do
      .form-group
        = hidden_field_tag :type, type
        = label_tag "Status"
        - options = Rails.application.config.on_types_info[type].dup
        - options.insert(0, 'All') if options[0] != 'All'
        = select_tag "status", options_for_select(options, params[:status]), {:class => "form-control", :onchange => "select_status()"}
      = submit_tag "submit", class: "inspection_filter_submit hide"

      %span.create_inspection{:id => 'accordion'}
        = link_to "<img src='/assets/ajax-loader.gif' class='ajax-loader hide'/>&nbsp;<i class='fa fa-plus'></i>Create Listing".html_safe, "#", {:class => "button btn btn-primary create_inspection", :on_type => @type, onclick: "create_inspection(event)"}

.row.tab-body-container.inspections
  = render "/inspections/inspection_tab_body", :inspections => inspections, :on_type => type

%script
  on_types = [];
  - on_types = Rails.application.config.on_types_info[type]
  - on_types.each do |t|
    on_types.push("#{t}");

  user_id = "#{current_user.id}";
  sale_type = "#{@type}";

:javascript
  $(document).ready(function() {
    init_for_sale();
  });

  //change label images
  function label_change() {  
    $("a[id^='status_']").on('save',function(event, params){
      console.log("gotcha");
      tag = $(event.target);
      inspection_id = tag.attr('data-pk');
      d = new Date();
      //tag = $(event.target).parents(".inspection_item");
      //console.log(tag);

      if (params.newValue == "For Sale")
      {
        $('img.property_image_label[inspection_id=' + inspection_id + ']').attr('src', '/assets/labels/for_sale.png?'+d.getTime());
      }
      if (params.newValue == "Sold")
      {
        $('img.property_image_label[inspection_id=' + inspection_id + ']').attr('src', '/assets/labels/sold.png?'+d.getTime());
      }
      if (params.newValue == "Disabled")
      {
        $('img.property_image_label[inspection_id=' + inspection_id + ']').attr('src', '/assets/labels/disabled.png?'+d.getTime());
      }
      if (params.newValue == "For Lease")
      {
        $('img.property_image_label[inspection_id=' + inspection_id + ']').attr('src', '/assets/labels/for_lease.png?'+d.getTime());
      }
      if (params.newValue == "Leased")
      {
        $('img.property_image_label[inspection_id=' + inspection_id + ']').attr('src', '/assets/labels/leased.png?'+d.getTime());
      }    
    });
  }
  //keep listing website in dropdown status
  function keep_dropdown() {
    $('.listing_website ul.dropdown-menu').click(function(e) {
      e.stopPropagation();
    });
  }

  function edit_listing_website(event){
    // Use jQuery.event.fix(event) to normalise event objects for cross browser support as e.preventDefault() is not supported by IE.
    event = $.event.fix(event);
    event.preventDefault();
    tag = $(event.target);
    inspection_id = tag.attr('data-pk');
    $("a#listing_url_" + inspection_id).trigger('click');
  }

  //display add website when listing website is empty
  function check_empty_website() {
    $('a.inline.visit_site').each(function(index, element){
      if($(element).attr('href') =='') {
        $(element).parent().parent().parent().find('#lstweb').html('<i class="fa fa-external-link"></i>');
        $(element).addClass('not-active');
      }
    })
  }

  function status_icon_change() {
  //change status icon when follow-up status changed
    $(".followup_type").each(function(index, element){
      switch ($.trim($(element).text()).toLowerCase()) {
        case "phone call":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-phone');
          break;
        case "newly registered":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-tablet');
          break;
        case "ipad follow-up":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-check');
          break;
        case "email sent":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-envelope-o');
          break;
        case "email requested":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-files-o');
          break;
        case "sold":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-key');
          break;
        case "newly added":
          $(element).prevAll(".followup_icon").find('i').removeClass().addClass('fa fa-lg fa-user-plus');
          break;      
      }
    });
  }

  function update_fa(event) {
    fa = event.target;
    if ($(fa).hasClass('fa-chevron-circle-down')) {
      $(fa).removeClass('fa-chevron-circle-down');
      $(fa).addClass('fa-chevron-circle-right');
      $(fa).closest('tr').removeClass('lead_expand');
    } else {
      $(fa).removeClass('fa-chevron-circle-right');
      $(fa).addClass('fa-chevron-circle-down');
      $(fa).closest('tr').addClass('lead_expand');
    }
    // toggle inspection_leads
    toggle_tag($(fa).parent());
  }

  function toggle_tag(this_tag) {
    id = this_tag.attr('href');
    tag = $(id);
    if (tag.hasClass('hide')) {
      tag.removeClass('hide');
      showAllEmailIcons(this_tag);
    }
    else
      tag.addClass('hide');
  }

  function detail_clk(event) {
    event.preventDefault();
    var tag = event.target;
    $(tag).find("i").click();
  }

  // Upload property file
  // $('a.upload_property_file').click(function(event){
  function upload_proerpty_file(event) {
    event = $.event.fix(event);
    event.preventDefault();
    console.log(event.target);
    // inspection_id = $(this).attr('inspection_id');
    inspection_id = $(event.target).attr('inspection_id');
    console.log("upload_property_file: " + inspection_id);
    $('input.property_file_' + inspection_id).click();
  }

  // The following are enough to load once only. If loaded multiple times during ajax, duplicate event will be registered
  $("a.bulk_email.inline").click(function(event){
    console.log('in init.bulk_email.inline click');
    console.log(event);
    inspection_id = $(this).attr('inspection_id');
    selected_leads = $('input.select_lead[inspection_id=' + inspection_id + ']:checked');
    // alert if no leads being selected
    if (selected_leads.length == 0) {
      bootbox.alert('Please select attendee(s) before sending email.');
      return false;
    }
  });

  //Update visit listing website url
  $("a[id^='listing_url_']").on('save', function(e, params){
    console.log('listing_url on save');
    tag = $(e.target);
    inspection_id = tag.attr('data-pk');
    new_url = params.newValue;
    tag.parent().parent().find("a.visit_site").attr('href',new_url).removeClass('not-active');;
    tag.parent().parent().parent().find("#lstweb").html('<i class="fa fa-external-link icon-blue"></i>');
    check_empty_website();
  });

app/views/inspections/_inspection_panel_body.html.haml
.tab-content
  - if on_type == 'Sale'
    - sale_class = 'active'
    - lease_class = ''
  - else
    - sale_class = ''
    - lease_class = 'active'
  - if on_type == 'Sale'
    #tab_for_sale.tab-pane.fade.in{:class => sale_class}
      =render '/inspections/for_sale', :inspections => inspections, :type => on_type
    #tab_for_lease.tab-pane.in.fade{:class => lease_class}
      / =render 'for_lease', :inspections => @inspections.where(:on_type => 'Lease')
  - else
    #tab_for_sale.tab-pane.fade.in{:class => sale_class}
      / =render 'for_sale', :inspections => @inspections.where(:on_type => 'Sale')
    #tab_for_lease.tab-pane.in.fade{:class => lease_class}
      =render '/inspections/for_sale', :inspections => inspections, :type => on_type

app/views/inspections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @inspection.address %>
</p>

<%= link_to 'Edit', edit_inspection_path(@inspection) %> |
<%= link_to 'Back', inspections_path %>